add some details to field/group/scalar doc
AleoHQ/welcome pull request #267
Opened 2023-08-28 06:18 UTC by bendyarm

In order for a developer to know what their code is supposed to do, it helps to know the
exact spec of the language.  For field and scalar values, it helps to know the maximum values.
For the group, the definition of `+` in terms of coordinates would be too verbose here,
but at least stating that it is a Twisted Edwards curve with specific `a` and `d` will let
someone look up the details and do the calculations.  Also specified the generator point.
I do not have the environment to make sure the html builds right, so I am hoping a reviewer
can check that before merging this branch.

2023-08-30 07:19 UTC, acoglio commented on documentation/leo/03_language.md
> +These are unsigned integers less than the modulus of the base field.  Showing the
```suggestion
These are unsigned integers less than the modulus of the base field.  The following are the
```

2023-08-30 07:20 UTC, acoglio approved these changes

2023-08-31 21:05 UTC, moAlobaidi approved these changes
Technically on PTO rn, but ran this locally and HTML renders correctly. LGTM!

2023-08-31 21:08 UTC, collinc97 requested changes
My comments add back double spaces at the end of lines in markdown.
This is desired because it starts the next sentence on a new line in the documentation - improving readability.

I believe your editor removes double spaces at the end of a line @bendyarm. Please address the changes and disable the feature in your editor in the future.

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +An import is declared as `import {ProgramID};`.
```suggestion
An import is declared as `import {ProgramID};`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A function is declared as `function {name}:`.
```suggestion
A function is declared as `function {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A function input is declared as `input {register} as {type}.{visibility};`.
```suggestion
A function input is declared as `input {register} as {type}.{visibility};`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A function output is declared as `output {register} as {type}.{visibility};`.
```suggestion
A function output is declared as `output {register} as {type}.{visibility};`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Use the `aleo run` CLI command to pass inputs to a function and execute the program.
```suggestion
Use the `aleo run` CLI command to pass inputs to a function and execute the program.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A closure is declared as `closure {name}:`.
```suggestion
A closure is declared as `closure {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A struct is a data type declared as `struct {name}:`.
```suggestion
A struct is a data type declared as `struct {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A [record](../concepts/02_records.md) type is declared as `record {name}:`.
```suggestion
A [record](../concepts/02_records.md) type is declared as `record {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Records contain component declarations `{name} as {type}.{visibility};`.
```suggestion
Records contain component declarations `{name} as {type}.{visibility};`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Record data structures must contain the `owner` declaration as shown below.
```suggestion
Record data structures must contain the `owner` declaration as shown below.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A mapping is declared as `mapping {name}:`.
```suggestion
A mapping is declared as `mapping {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +A finalize is declared as `finalize {name}:`.
```suggestion
A finalize is declared as `finalize {name}:`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +a finalize *finalizes* a function on chain.
```suggestion
a finalize *finalizes* a function on chain.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Upon success of the finalize function, the program logic is executed.
```suggestion
Upon success of the finalize function, the program logic is executed.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Upon failure of the finalize function, the program logic is reverted.
```suggestion
Upon failure of the finalize function, the program logic is reverted.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +The `self.caller` command returns the address of the caller of the program.
```suggestion
The `self.caller` command returns the address of the caller of the program.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +The `rand.chacha` command returns a random number generated by the [ChaCha20 algorithm](http://cr.yp.to/chacha.html).
```suggestion
The `rand.chacha` command returns a random number generated by the [ChaCha20 algorithm](http://cr.yp.to/chacha.html).  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +This command supports sampling a random `address`, `boolean`, `field`, `group`, `i8`, `i16`, `i32`, `i64`, `i128`, `u8`, `u16`, `u32`, `u64`, `u128`, and `scalar`.
```suggestion
This command supports sampling a random `address`, `boolean`, `field`, `group`, `i8`, `i16`, `i32`, `i64`, `i128`, `u8`, `u16`, `u32`, `u64`, `u128`, and `scalar`.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Up to two additional seeds can be provided to the `rand.chacha` command.
```suggestion
Up to two additional seeds can be provided to the `rand.chacha` command.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +Aleo Instructions supports the following syntax for committing to standard types.
```suggestion
Aleo Instructions supports the following syntax for committing to standard types.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +The `position` command, e.g. `position exit`, indicates a point to branch execution to.
```suggestion
The `position` command, e.g. `position exit`, indicates a point to branch execution to.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/aleo/03_language.md
> +The `branch.eq` command, e.g. `branch.eq r0 r1 to exit`, which branches execution to the position indicated by `exit` if `r0` and `r1` are equal.
```suggestion
The `branch.eq` command, e.g. `branch.eq r0 r1 to exit`, which branches execution to the position indicated by `exit` if `r0` and `r1` are equal.  
```

2023-08-31 21:08 UTC, collinc97 commented on documentation/leo/03_language.md
> +Leo will not default to an integer type. The definition of a integer **must** include an explicit type.
```suggestion
Leo will not default to an integer type. The definition of a integer **must** include an explicit type.  
```

2023-09-01 23:27 UTC, bendyarm commented
@collinc97 Thanks for catching that.
I undid all the end-of-line space removals so the comparison now is just the changed sections.

2023-09-05 18:20 UTC, collinc97 approved these changes

2023-09-05 18:21 UTC, merged