Update self.caller and self.signer documentation
AleoHQ/welcome pull request #288
Opened 2023-10-02 20:23 UTC by craigjson

2023-10-03 03:48 UTC, collinc97 requested changes
Thanks for the PR @craigjson 

I think the motivating example is a good way to introduce this command.
Do you think developers will copy and paste this example into their projects?
Do you have additional snarkvm CLI commands that you ran to test the functionality?

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    gates as u64.private;
```suggestion
```

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    gates as u64.private;
```suggestion
```

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    owner as address.private;
```suggestion
    // The address of the owner.
    owner as address.private;
```

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    owner as address.private;
```suggestion
    // The address of the owner.
    owner as address.private;
```

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +
Can you add a comment explaining the purpose of this program?

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
Can you add some executable snarkvm CLI commands that will work when this program is copied and pasted into a project?

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    // self.signer, should be original invoker of the program calling this one
```suggestion
    // The address of the caller.
```
It's not clear to me why this "should be the original invoker of the program".
`caller` is a private address within a record data type.
I can import this record into another program and set `caller` to any arbitrary address.
`caller` cannot be restricted to a specific address at this point in the program.

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    // self.caller, should be the direct program address calling this one
```suggestion
    // The address of the parent.
```
Please see my previous comment on line 454

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +
Please add a comment describing what this function computes and returns.

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    // self.signer, should be original invoker of the program calling this one
```suggestion
    // The address of the caller.
```
Please see my previous comment on line 454

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +    parent as address.private;
```suggestion
    // The address of the parent.
```
Please see my previous comment on line 454

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +
Can you add a comment explaining the purpose of this program?

2023-10-03 03:48 UTC, collinc97 commented on documentation/aleo/03_language.md
> +
Please add a comment describing what this function computes and returns.

2023-10-03 03:50 UTC, collinc97 commented
> Makes the following updates to the `.aleo` documentation
> 
> 1. Updates existing references to `self.caller` to reference `self.signer`
> 2. Adds a section for `self.caller` explaining the new feature
> 3. Provides examples of the difference between `self.signer` and `self.caller`
> 
> One question, with this update, there will be inconsistency between the `Leo` and `Aleo` documentation. Namely, that because Leo has not yet implemented the new `self.caller`, the documentation that refers to it https://developer.aleo.org/leo/language#selfcaller will actually be talking about `self.signer` in Aleo instructions. I worry this may cause some confusion. We could remove this section in the Leo docs for now, curious to your thoughts @collinc97
> 
> Part of: [AleoHQ/snarkVM#2020](https://github.com/AleoHQ/snarkVM/pull/2020)

I expect the feature parity between Leo and Aleo Instructions to be resolved this week.
For now you could add an [Admonition](https://docusaurus.io/docs/markdown-features/admonitions) that makes it clear for people that there is a difference.

2023-10-03 17:49 UTC, craigjson commented
> Thanks for the PR @craigjson
> 
> I think the motivating example is a good way to introduce this command. Do you think developers will copy and paste this example into their projects? Do you have additional snarkvm CLI commands that you ran to test the functionality?

A developer can copy and paste this example, however I'd say it's fairly academic and limited in it's usability for a production program. It reminds me of an example a professor would use to show how OOP Inheritance works.

I added some steps to create a project and run this on the CLI to generate the output that is provided

2023-10-04 04:34 UTC, collinc97 commented
Hi @craigjson can you see my latest PR against this one https://github.com/AleoHQ/welcome/pull/291

2023-10-04 05:59 UTC, craigjson commented
> Hi @craigjson can you see my latest PR against this one #291

merged

2023-10-04 18:24 UTC, collinc97 approved these changes
LGTM

2023-10-04 18:25 UTC, merged